import {assetUrl} from './assetUrl.js';
import { useEffect, useRef, useState } from 'react';
import { ArrowCounterClockwise, ArrowRight, BookOpen, Check, Copy, DownloadSimple, Flower, FolderOpen, Info, Microphone, Moon, Pause, Play, SlidersHorizontal, Sparkle, Stop, UploadSimple, Waveform, X } from '@phosphor-icons/react';
import { WaterScene } from './WaterScene.jsx';
import { useStudioAudio } from './useStudioAudio.js';
import { saveProject, listProjects, getProject, exportProject, importProject } from './projectStore.js';

const MODES = { sea: '月光造境', paper: '诗笺工坊', sound: '声音成诗' };
const POEMS = {
  wang: { title: '望月怀远', author: '唐 · 张九龄', lines: ['海上生明月', '天涯共此时'], next: ['情人怨遥夜', '竟夕起相思'], context: '借同一轮明月，表达相隔天涯的思念。这是一首咏月怀人的诗。', source: 'https://www.ihchina.cn/project_details/9810' },
  su: { title: '水调歌头', author: '宋 · 苏轼', lines: ['但愿人长久', '千里共婵娟'], next: ['人有悲欢离合', '月有阴晴圆缺'], context: '小序写道：“丙辰中秋，欢饮达旦，大醉，作此篇，兼怀子由。”这首词将中秋月色与对弟弟的思念相连。', source: 'https://www.beijing.gov.cn/renwen/zt/wmdjr/zqj/202303/t20230303_2928408.html' },
  li: { title: '月下独酌', author: '唐 · 李白', lines: ['举杯邀明月', '对影成三人'], next: ['我歌月徘徊', '我舞影零乱'], context: '诗人把明月和自己的影子想象为同伴。这是咏月文学，不能据此认定诗作写于中秋。', source: 'https://www.sastind.gov.cn/history/n152/n81023/n81097/c112089/content.html' },
};
const defaults = mode => ({ poemId: mode === 'paper' ? 'su' : mode === 'sound' ? 'custom' : 'wang', message: mode === 'sea' ? '今晚，让月光替我到你身旁。' : mode === 'paper' ? '晚风经过的地方，有我想念的人。' : '月光落在旧窗前，\n我把想念读给你听。', customPoem: '把思念，读给月亮听。', moonX: mode === 'paper' ? .24 : .7, moonY: mode === 'paper' ? .31 : mode === 'sound' ? .21 : .23, moonSize: mode === 'paper' ? .2 : mode === 'sound' ? .145 : .16, brightness: .65, response: 'message', trigger: mode === 'paper' ? 'flower' : 'moon', spacing: .6, intensity: .55, textX: mode === 'paper' ? .49 : mode === 'sound' ? .18 : .075, textY: mode === 'paper' ? .19 : mode === 'sound' ? .3 : .17 });
const initial = mode => ({ id: crypto.randomUUID(), title: mode === 'sea' ? '把月光寄给你' : mode === 'paper' ? '我的月下诗笺' : '一段声音，一片月光', mode, config: defaults(mode), audioBlob: null, audioLabel: '', updatedAt: Date.now() });
const clamp = (v, min, max) => Math.min(max, Math.max(min, v));
const stampTime = t => `${Math.floor((t || 0) / 60).toString().padStart(2, '0')}:${Math.floor((t || 0) % 60).toString().padStart(2, '0')}`;

function WaveMeter({ analysisRef, playing }) {
  const ref = useRef(null);
  useEffect(() => { let frame; const draw = () => { const c = ref.current; if (!c) return; const ctx = c.getContext('2d'); ctx.clearRect(0, 0, c.width, c.height); const bins = analysisRef.current.bins; ctx.fillStyle = '#9db5c8'; for (let i = 0; i < 88; i++) { const amp = playing && bins ? bins[Math.min(bins.length - 1, i * 2)] / 255 : 0; const height = 2 + amp * (c.height - 5); ctx.fillRect(i * c.width / 88, (c.height - height) / 2, 2, height); } frame = requestAnimationFrame(draw); }; draw(); return () => cancelAnimationFrame(frame); }, [analysisRef, playing]);
  return <canvas ref={ref} width="440" height="38" className="wave-meter" aria-label={playing ? '正在显示音频的实际频谱' : '音频已暂停'} />;
}
function Modal({ title, onClose, children, wide = false }) {
  const dialog = useRef(null);
  useEffect(() => { const el = dialog.current; el.showModal(); const cancel = e => { e.preventDefault(); onClose(); }; el.addEventListener('cancel', cancel); return () => { el.removeEventListener('cancel', cancel); el.close(); }; }, []);
  return <dialog className={`modal ${wide ? 'wide' : ''}`} ref={dialog} onClick={e => e.target === dialog.current && onClose()}><div className="modal-heading"><h2>{title}</h2><button aria-label="关闭对话框" className="icon-button" onClick={onClose}><X size={22} /></button></div>{children}</dialog>;
}

export function App({active=true}) {
  const [mode, setMode] = useState(() => Object.hasOwn(MODES, location.hash.slice(1)) ? location.hash.slice(1) : 'sea');
  const [projects, setProjects] = useState(() => ({ sea: initial('sea'), paper: initial('paper'), sound: initial('sound') }));
  const [experience, setExperience] = useState(false), [revealed, setRevealed] = useState(false), [nextVerse, setNextVerse] = useState(false);
  const [ripple, setRipple] = useState(0), [modal, setModal] = useState(null), [saved, setSaved] = useState([]), [toast, setToast] = useState('');
  const [exported, setExported] = useState(null);
  const [saving, setSaving] = useState(false), [advanced, setAdvanced] = useState(false), [history, setHistory] = useState({ sea: [], paper: [], sound: [] }), [dirtyModes, setDirtyModes] = useState({sea:false,paper:false,sound:false});
  const audio = useStudioAudio();
  const stageRef = useRef(null), drag = useRef(null), toastTimer = useRef(null), audioInput = useRef(null), projectInput = useRef(null);
  const project = projects[mode], config = project.config, poem = POEMS[config.poemId];
  const projectsRef = useRef(projects), audioLatest = useRef(audio); projectsRef.current = projects; audioLatest.current = audio;
  const dirty = dirtyModes[mode];
  const setDirty = value => setDirtyModes(d => ({...d,[mode]:value}));
  const customLines = (config.customPoem || '写下属于你的月光').split(/\n/).filter(Boolean);
  const lines = poem ? (nextVerse ? poem.next : poem.lines) : nextVerse ? [customLines[1] || config.message || customLines[0]] : customLines.slice(0, 3);
  const notify = message => { clearTimeout(toastTimer.current); setToast(message); toastTimer.current = setTimeout(() => setToast(''), 4000); };
  const remember = () => setHistory(h => ({ ...h, [mode]: [...h[mode].slice(-29), { ...config }] }));
  const patch = change => { setProjects(p => ({ ...p, [mode]: { ...p[mode], config: { ...p[mode].config, ...change } } })); setDirty(true); };
  const change = value => { remember(); patch(value); };
  const switchMode = value => { setMode(value); location.hash = value; setExperience(false); setRevealed(false); setNextVerse(false); setAdvanced(false); };
  useEffect(() => { const onHash = () => { const next = location.hash.slice(1); if (Object.hasOwn(MODES, next)) setMode(next); }; window.addEventListener('hashchange', onHash); return () => { window.removeEventListener('hashchange', onHash); clearTimeout(toastTimer.current); }; }, []);
  useEffect(() => { if (mode !== 'sound' || !active) audio.stop(); }, [mode, audio.stop, active]);
  useEffect(() => { if (audio.recording) setDirtyModes(d => ({ ...d, sound: true })); }, [audio.recording]);
  useEffect(() => { if (audio.error) notify(audio.error); }, [audio.error]);
  const undo = () => { const entries = history[mode]; if (!entries.length) return; patch(entries.at(-1)); setHistory(h => ({ ...h, [mode]: h[mode].slice(0, -1) })); };
  const interact = target => { if (target !== config.trigger) return; if (config.response === 'message') setRevealed(v => !v); if (config.response === 'next') setNextVerse(v => !v); setRipple(v => v + 1); };
  const moveBounds = (target, node) => {
    const stage = stageRef.current.getBoundingClientRect();
    const size = node.getBoundingClientRect();
    if (target === 'moon') {
      const halfWidth = size.width / stage.width / 2, halfHeight = size.height / stage.height / 2;
      return {minX:Math.max(.1,halfWidth),maxX:Math.min(.9,1-halfWidth),minY:Math.max(.1,halfHeight),maxY:.48};
    }
    return {minX:.03,maxX:Math.max(.03,Math.min(.8,.97-size.width/stage.width)),minY:.06,maxY:Math.max(.06,Math.min(.75,.95-size.height/stage.height))};
  };
  const startDrag = (event, target) => { if (event.button !== 0 || experience && target === 'text') return; event.stopPropagation(); remember(); drag.current = { target, sx:event.clientX, sy:event.clientY, x:target === 'moon' ? config.moonX : config.textX, y:target === 'moon' ? config.moonY : config.textY, rect:stageRef.current.getBoundingClientRect(), bounds:moveBounds(target,event.currentTarget), moved:false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveDrag = event => { const d = drag.current; if (!d) return; const dx = (event.clientX-d.sx)/d.rect.width, dy = (event.clientY-d.sy)/d.rect.height; if(Math.abs(dx)+Math.abs(dy)>.007)d.moved=true; const x=d.target==='moon'?'moonX':'textX',y=d.target==='moon'?'moonY':'textY'; patch({[x]:clamp(d.x+dx,d.bounds.minX,d.bounds.maxX),[y]:clamp(d.y+dy,d.bounds.minY,d.bounds.maxY)}); };
  const endDrag = event => { const d=drag.current;if(!d)return;drag.current=null;event.currentTarget.releasePointerCapture(event.pointerId);if(!d.moved&&d.target==='moon')interact('moon'); };
  const keyMove = (event,target) => { const arrows={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]};if(arrows[event.key]){event.preventDefault();const[dx,dy]=arrows[event.key],b=moveBounds(target,event.currentTarget),x=target==='moon'?'moonX':'textX',y=target==='moon'?'moonY':'textY';change({[x]:clamp(config[x]+dx,b.minX,b.maxX),[y]:clamp(config[y]+dy,b.minY,b.maxY)});}if(target==='moon'&&['Enter',' '].includes(event.key)){event.preventDefault();interact('moon');} };
  const currentRecord = () => ({ ...project, audioBlob: mode === 'sound' ? audio.blob : null, audioLabel: mode === 'sound' ? audio.label : '', updatedAt: Date.now() });
  const save = async () => { setSaving(true); const snapshot = currentRecord(); try { const record = await saveProject(snapshot); const latest = projectsRef.current[mode]; if (latest.id === snapshot.id && latest.config === snapshot.config && latest.title === snapshot.title && (mode !== 'sound' || audioLatest.current.blob === snapshot.audioBlob)) setDirty(false); setProjects(p => p[mode].id === snapshot.id ? ({ ...p, [mode]: {...p[mode],updatedAt:record.updatedAt} }) : p); notify('已保存到这个浏览器 · 可在“我的作品”中继续创作'); } catch (e) { notify(e.message); } finally { setSaving(false); } };
  const showWorks = async () => { try { setSaved(await listProjects()); setModal('works'); } catch (e) { notify(e.message); } };
  const preserveDraft = async targetMode => { if (!dirtyModes[targetMode]) return; const draft = projectsRef.current[targetMode]; await saveProject({...draft,audioBlob:targetMode === 'sound' ? audioLatest.current.blob : null,audioLabel:targetMode === 'sound' ? audioLatest.current.label : ''}); };
  const openWork = async id => { try { const record = await getProject(id); if (!record) return notify('没有找到这件作品'); await preserveDraft(record.mode); if (record.mode === 'sound' && !(await audio.loadBlob(record.audioBlob, record.audioLabel))) return notify('这件作品的声音未能载入，已保留当前作品'); setProjects(p => ({ ...p, [record.mode]: record })); setHistory(h=>({...h,[record.mode]:[]})); setDirtyModes(d=>({...d,[record.mode]:false})); switchMode(record.mode); setModal(null); notify('作品已打开，可以继续创作'); } catch (e) { notify(e.message); } };
  const remix = async () => { try { await saveProject(currentRecord()); const record = { ...currentRecord(), id: crypto.randomUUID(), title: `${project.title.replace(/ · 改编$/, '').slice(0,43)} · 改编`, config: { ...config }, originTitle: project.title }; setProjects(p => ({ ...p, [mode]: record })); setHistory(h=>({...h,[mode]:[]})); setExperience(false); setDirty(true); notify('原作品已保存，已创建独立副本供你改编'); } catch(e) { notify(e.message); } };
  const download = async () => { try { const text = await exportProject(currentRecord()); setExported({text, name:`${project.title.replace(/[\\/:*?"<>|]/g, '-')}.moon.json`}); setModal('export'); } catch (e) { notify(e.message); } };
  const downloadFile = () => { const link = document.createElement('a'); const url = URL.createObjectURL(new Blob([exported.text], {type:'application/json'})); link.href = url; link.download = exported.name; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url),10000); notify('已请求下载；也可以复制下方作品内容'); };
  const copyExport = async () => { try { await navigator.clipboard.writeText(exported.text); notify('作品内容已复制，可保存为 .moon.json 文件'); } catch { notify('请选中下方作品内容，手动复制'); } };
  const importWork = async file => { if (!file) return; try { if (file.size > 30 * 1024 * 1024) throw Error('作品文件不能超过30MB'); const record = await importProject(await file.text()); if(record.audioBlob?.size > 20*1024*1024) throw Error('作品中的音频不能超过20MB'); await preserveDraft(record.mode); if (record.mode === 'sound' && !(await audio.loadBlob(record.audioBlob, record.audioLabel))) throw Error('这件作品的音频无法载入，请检查文件'); await saveProject(record); setProjects(p => ({ ...p, [record.mode]: record })); setHistory(h=>({...h,[record.mode]:[]})); setDirtyModes(d=>({...d,[record.mode]:false})); switchMode(record.mode); setModal(null); notify('导入成功，已作为一件新作品保存'); } catch (e) { notify(e.message); } };

  const range = (name, field, min = 0, max = 1, step = .01) => <label className="range-control"><span>{name}<output>{Math.round(config[field] * 100)}</output></span><input type="range" aria-label={name} min={min} max={max} step={step} value={config[field]} onPointerDown={remember} onKeyDown={e => ['ArrowLeft', 'ArrowRight'].includes(e.key) && remember()} onChange={e => patch({ [field]: Number(e.target.value) })} /></label>;
  const actionControls = <><div className="action-row"><select aria-label="触发方式" value={config.trigger} onChange={e => change({ trigger: e.target.value })}><option value="moon">点击月亮</option>{mode === 'paper' && <option value="flower">点开桂花</option>}<option value="stage">点击画面</option></select><ArrowRight size={17} /><select aria-label="画面回应" value={config.response} onChange={e => change({ response: e.target.value })}><option value="message">显示我的寄语</option><option value="next">展开下一句诗</option><option value="ripple">{mode === 'paper' ? '月光漫过纸面' : '泛起月光涟漪'}</option></select></div><button className="text-button accent" onClick={() => { setExperience(true); setRevealed(false); setNextVerse(false); }}><Play size={17} />试一试这个动作</button></>;
  const poemControls = <><h2 className="section-title">诗意起点</h2><div className="select-wrap"><select aria-label="选择诗词" value={config.poemId} onChange={e => { change({ poemId: e.target.value }); setNextVerse(false); }}>{Object.entries(POEMS).map(([key, p]) => <option key={key} value={key}>{p.title} / {p.author.split(' · ')[1]}</option>)}<option value="custom">写下自己的诗</option></select></div>{config.poemId === 'custom' ? <textarea className="custom-poem-input" aria-label="我的诗句" value={config.customPoem} maxLength={100} onFocus={remember} onChange={e => patch({ customPoem: e.target.value })} /> : <button className="text-button source-link" onClick={() => setModal('source')}><BookOpen size={18} />原文与出处</button>}</>;
  const messageControl = (sound = false) => <div className="message-control"><label className="section-title" htmlFor="message">{sound ? '写下你的两句诗' : '我的表达'}</label>{sound && <p className="subtle">让你的文字，随着声音，在月光中生长。</p>}<div className="textarea-wrap"><textarea id="message" aria-label={sound ? '我的声音诗' : '我的表达'} maxLength={200} value={config.message} onFocus={remember} onChange={e => patch({ message: e.target.value })} /><span>{config.message.length} / 200</span></div>{sound && <small className="subtle">来源：用户原创 · 内容可以自由修改</small>}</div>;
  const artwork = <div ref={stageRef} className={`artwork ${mode}-artwork ${experience ? 'is-experiencing' : ''}`} onClick={() => interact('stage')} data-testid="artwork">
    {mode === 'paper' ? <img className="paper-background" src={assetUrl('/assets/paper-scene.png')} alt="象牙色纸笺，浅墨山水与桂花" /> : active && <WaterScene mode={mode} moon={{ x: config.moonX, y: config.moonY, size: config.moonSize, brightness: config.brightness }} audioStateRef={audio.analysisRef} ripple={ripple} intensity={config.intensity} />}
    <button className={`moon-object ${mode === 'paper' ? 'jade-moon' : ''}`} data-testid="moon-object" aria-label="月亮：拖动或用方向键移动，按回车触发动作" style={{ left: `${config.moonX * 100}%`, top: `${config.moonY * 100}%`, width: `${config.moonSize * 100}%`, filter: mode === 'paper' ? `sepia(.7) hue-rotate(75deg) saturate(.6) brightness(${.62 + config.brightness * .32})` : `brightness(${.55 + config.brightness * .8})` }} onPointerDown={e => startDrag(e, 'moon')} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={() => { drag.current = null; }} onClick={e => e.stopPropagation()} onKeyDown={e => keyMove(e, 'moon')}><img src={assetUrl('/assets/moon.png')} draggable="false" alt="月亮" />{!experience && <span className="moon-hint">拖动月亮</span>}</button>
    <div className={`poem-composition ${mode === 'paper' ? 'vertical-poem' : ''} ${nextVerse ? 'verse-shift' : ''} ${!poem ? 'custom-verse' : ''}`} data-testid="poem-composition" role="group" tabIndex={experience ? -1 : 0} aria-label="诗句：拖动或用方向键调整位置" style={{ left: `${config.textX * 100}%`, top: `${config.textY * 100}%`, '--poem-spacing': `${.03 + config.spacing * .14}em` }} onPointerDown={e => startDrag(e, 'text')} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={() => { drag.current = null; }} onKeyDown={e => keyMove(e, 'text')} onClick={e => e.stopPropagation()}><h1>{lines.map((line, i) => <span key={`${i}-${line}`}>{line}</span>)}</h1><p className="poem-credit">{poem ? `${poem.author}《${poem.title}》` : mode === 'sound' ? '我的声音诗 · 用户原创' : '我的诗 · 用户原创'}</p>{mode === 'sound' && <p className="sound-authored-lines">{config.message}</p>}{!experience && mode === 'paper' && <small className="poem-drag-hint">拖动诗句，自由编排</small>}</div>
    {mode === 'paper' && <button aria-label="点开桂花" className="flower-hotspot" onClick={e => { e.stopPropagation(); interact('flower'); }}><Flower size={23} /><span>{experience ? '轻触桂花' : '点开桂花'}</span></button>}
    {(revealed && mode !== 'sound' || mode === 'paper' && !experience) && <div className={`personal-message ${revealed ? 'message-visible' : ''}`} data-testid="revealed-message">{config.message}</div>}
    {config.response === 'ripple' && mode === 'paper' && ripple > 0 && <img key={ripple} className="paper-light-wave" src={assetUrl('/assets/moon.png')} alt="" style={{left:`${config.moonX*100}%`,top:`${config.moonY*100}%`}} />}
    {mode === 'sound' && <div className="art-audio-player" onClick={e => e.stopPropagation()}><button className="play-orb" aria-label={audio.playing ? '暂停音频' : '播放音频'} onClick={audio.togglePlay}>{audio.playing ? <Pause size={23} weight="fill" /> : <Play size={23} weight="fill" />}</button>{active && <WaveMeter analysisRef={audio.analysisRef} playing={audio.playing || audio.recording} />}<span>{stampTime(audio.time)} / {stampTime(audio.duration)}</span><small>声音，化作水纹；文字，浮于月下。</small></div>}
    {mode === 'sea' && <p className="art-hint">{experience ? '轻触或拖动月亮，发现藏在月色里的心意' : '试着拖动，让月光落在你的方向'}</p>}
    {experience && <button className="experience-remix" onClick={e => { e.stopPropagation(); remix(); }}><Copy size={17} />以此继续创作</button>}
  </div>;

  return <main className={`studio theme-${mode} ${experience ? 'experience-mode' : ''}`}>
    <header className="topbar"><a className="brand" href="#sea" onClick={e => { e.preventDefault(); switchMode('sea'); }}>月下造境<span>以诗为境 · 与月共鸣</span></a><nav className="mode-switch" aria-label="创作风格">{Object.entries(MODES).map(([key, label]) => <button key={key} aria-pressed={mode === key} onClick={() => switchMode(key)}>{label}</button>)}</nav><div className="top-actions"><a className="text-button" href="#letters">月光来信</a><button className="text-button works-button" onClick={showWorks}><FolderOpen size={18} />我的作品</button><button className="text-button preview-button" onClick={() => { setExperience(v => !v); setRevealed(false); setNextVerse(false); }}>{experience ? '返回创作' : '体验作品'}</button><button className="primary-button" onClick={save} disabled={saving || (mode === 'sound' && audio.recording)}>{saving ? '正在保存' : <><Check size={17} />保存作品</>}</button></div></header>
    <audio ref={audio.audioRef} preload="metadata" />
    <input type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.webm" hidden ref={audioInput} onChange={async e => { const f = e.target.files[0]; if (f) await audio.importFile(f); e.target.value = ''; setDirty(true); }} />
    <input type="file" accept=".json,.moon.json,application/json" hidden ref={projectInput} onChange={e => { importWork(e.target.files[0]); e.target.value = ''; }} />
    {mode !== 'sound' ? <div className={`main-layout ${mode}-layout`}>
      {!experience && <aside className="editor-panel"><section>{poemControls}</section><section>{messageControl()}</section><section><h2 className="section-title">{mode === 'paper' ? '作品怎样展开' : '让画面回应'}</h2>{actionControls}{range(mode === 'paper' ? '字间留白' : '月光亮度', mode === 'paper' ? 'spacing' : 'brightness')}<button className="text-button" onClick={() => setAdvanced(v => !v)} aria-expanded={advanced}><SlidersHorizontal size={18} />{advanced ? '收起画面设置' : '更多画面设置'}</button>{advanced && <div className="advanced-controls">{range('月亮大小', 'moonSize', .07, .24, .005)}{mode === 'paper' ? range('月光亮度', 'brightness') : range('字间留白', 'spacing')}</div>}</section><div className="panel-bottom"><button className="text-button" onClick={undo} disabled={!history[mode].length}><ArrowCounterClockwise size={20} />撤销</button><button className="text-button" onClick={() => setModal('guide')}><Info size={18} />创作提示</button></div></aside>}
      <div className="art-workbench">{artwork}{mode === 'paper' && !experience && <div className="paper-tools"><button onClick={() => document.getElementById('message')?.focus()}><BookOpen size={25} /><span>字句</span></button><button onClick={() => setAdvanced(v => !v)}><Moon size={25} /><span>景物</span></button><button onClick={() => { setExperience(true); setRevealed(false); }}><Sparkle size={25} /><span>体验动作</span></button></div>}</div>
    </div> : <div className="sound-layout"><div className="project-subbar"><div><input aria-label="作品名称" value={project.title} maxLength={50} onChange={e => { setProjects(p => ({ ...p, [mode]: { ...p[mode], title: e.target.value } })); setDirty(true); }} /><button className="text-button accent" onClick={remix}>以此继续创作<ArrowRight size={15} /></button></div><span className="subtle">{audio.label}</span></div>{artwork}{!experience && <div className="sound-controls">{messageControl(true)}<section className="sound-response"><h2 className="section-title">让声音改变画面</h2><p className="subtle">录下你的声音，或导入音频，让水纹随声音起伏。</p><div className="sound-buttons"><button className="primary-button" onClick={audio.toggleRecord}>{audio.recording ? <Stop size={22} weight="fill" /> : <Microphone size={22} />}{audio.recording ? '停止录音' : '录一段'}</button><button className="outline-button" onClick={() => audioInput.current.click()} disabled={audio.recording}><FolderOpen size={23} />导入音频</button><button className="outline-button" onClick={audio.togglePlay} disabled={audio.recording}>{audio.playing ? <Pause size={22} /> : <Play size={22} />}{audio.playing ? '暂停' : '试听'}</button></div><div className="sound-mapping"><span>声音起伏</span><ArrowRight size={18} /><Waveform size={28} /><ArrowRight size={18} /><span>水纹扩散</span><button className="text-button" onClick={() => setAdvanced(v => !v)}><SlidersHorizontal size={16} />画面设置</button></div>{range('回应强度', 'intensity')}{advanced && <div className="sound-advanced"><label>画面上的诗句<input aria-label="声音版画面诗句" value={config.customPoem} maxLength={100} onFocus={remember} onChange={e => patch({ customPoem: e.target.value })} /></label>{range('月光亮度', 'brightness')}</div>}<small className="subtle">{audio.recording ? '正在录音 · 最长60秒，结束后可试听' : '声音保存在当前设备，保存作品时一并保留。'}</small></section></div>}</div>}
    {!experience && <footer className="studio-footer"><span>{dirty ? '有未保存的修改' : '属于你的月光，等你落款'}<span className="footer-dot">·</span>作品保存在这个浏览器</span><div><button onClick={() => setModal('rename')}>作品命名</button><button onClick={download}><DownloadSimple size={15} />导出作品</button><button onClick={() => projectInput.current.click()}><UploadSimple size={15} />导入作品</button></div></footer>}
    {toast && <div role="status" className="toast"><Check size={18} />{toast}</div>}
    {modal === 'export' && exported && <Modal title="导出作品" onClose={() => setModal(null)}><p>文字、画面设置和导入的声音已打包。下载后可在另一台设备导入，继续创作。</p><p className="subtle export-filename">{exported.name} · {Math.ceil(new Blob([exported.text]).size / 1024)} KB</p><div className="export-actions"><button className="primary-button" onClick={downloadFile}><DownloadSimple size={18} />下载作品文件</button><button className="outline-button" onClick={copyExport}><Copy size={18} />复制作品内容</button></div><details className="export-details"><summary>查看可复制的作品内容</summary><textarea aria-label="作品文件内容" readOnly value={exported.text} onFocus={e => e.currentTarget.select()} /></details><p className="modal-note">文件保留可编辑的创作内容。若当前浏览器无法下载，可复制内容并保存为 .moon.json 文件。</p></Modal>}
    {modal === 'source' && <Modal title={poem?.title || '我的诗'} onClose={() => setModal(null)}><p className="source-author">{poem?.author}</p><div className="source-poem">{poem?.lines.map(line => <p key={line}>{line}</p>)}</div><p>{poem?.context}</p><a className="source-external" href={poem?.source} target="_blank" rel="noreferrer">阅读文化资料与原文<ArrowRight size={17} /></a><p className="modal-note">原文保留作者与出处。你加入的寄语和互动，是属于你的当代创作。</p></Modal>}
    {modal === 'guide' && <Modal title="从一句诗，造一片月光" onClose={() => setModal(null)}><ol className="guide-list"><li><strong>让诗意成为起点</strong><p>选择一首诗，或写自己的句子。将想说的话放进“我的表达”。</p></li><li><strong>亲手编排画面</strong><p>拖动月亮和诗句，也可以选中后使用方向键。调整光线与留白。</p></li><li><strong>让别人参与</strong><p>选择点击对象和回应方式，点“体验作品”查看观看效果。</p></li><li><strong>让作品继续生长</strong><p>保存、复制改编，或导出作品文件交给朋友导入。当前版本不生成公开分享链接。</p></li></ol><a href="https://www.ihchina.cn/project_details/9810" target="_blank" rel="noreferrer" className="source-external">了解中秋的源流与习俗<ArrowRight size={17} /></a></Modal>}
    {modal === 'rename' && <Modal title="为这片月光命名" onClose={() => setModal(null)}><label className="rename-label">作品名称<input autoFocus maxLength={50} value={project.title} onChange={e => { setProjects(p => ({ ...p, [mode]: { ...p[mode], title: e.target.value } })); setDirty(true); }} /></label><button className="primary-button modal-primary" onClick={() => setModal(null)}>完成</button></Modal>}
    {modal === 'works' && <Modal title="我的作品" wide onClose={() => setModal(null)}><p className="subtle">这里收藏着你在这个浏览器保存的作品。</p>{saved.length ? <div className="saved-grid">{saved.map(item => <button className="saved-work" key={item.id} onClick={() => openWork(item.id)}><div className={`saved-cover saved-${item.mode}`}><img src={assetUrl(`/assets/${item.mode === 'sea' ? 'moon-sea' : item.mode === 'paper' ? 'paper-scene' : 'sound-pool'}.png`)} alt="" /><span>{item.config.poemId === 'custom' ? item.config.customPoem : POEMS[item.config.poemId]?.lines[0]}</span></div><strong>{item.title}</strong><small>{MODES[item.mode]} · {new Date(item.updatedAt).toLocaleDateString('zh-CN')}</small></button>)}</div> : <div className="empty-works"><Moon size={45} /><h3>第一片月光，还等着你</h3><p>完成创作后，点击“保存作品”，就能在这里找到它。</p></div>}<div className="modal-actions"><button className="outline-button" onClick={() => projectInput.current.click()}><UploadSimple size={18} />导入一件作品</button><button className="primary-button" onClick={() => setModal(null)}>回到创作</button></div></Modal>}
  </main>;
}
