import {assetUrl} from './assetUrl.js';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,Copy,DownloadSimple,EnvelopeOpen,FolderOpen,Heart,Mailbox,Moon,PenNib,Plus,SealCheck,Users, X} from '@phosphor-icons/react';
import {createLetter,validateLetter,saveLetter,listLetters,getLetter,exportInvitation,importInvitation,submitReply,exportReply,mergeReply,remixLetter} from './letterStore.js';
import {LetterArtifact} from './LetterArtifact.jsx';
import {LETTER_POEMS,LETTER_STYLES,OPENINGS,SAMPLE_FIELDS} from './letterContent.js';
import './letters.css';

const SESSION_KEY='moon-letter-session-v1';
const EMPTY_REPLY={name:'',city:'',line:'',message:''};
function restore(){try{const s=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(s&&['compose','invite','receive','read','result'].includes(s.view)&&s.letter){const l=validateLetter(s.letter);return {...s,letter:l};}}catch{}return null;}
function Dialog({title,children,onClose}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();},[]);return <dialog className="ml-dialog" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>e.target===ref.current&&onClose()}><header><h2>{title}</h2><button type="button" className="ml-icon" aria-label="关闭对话框" onClick={onClose}><X size={23}/></button></header>{children}</dialog>;}
function Field({label,name,value,onChange,limit=40,placeholder,area=false,rows=4,hint,required=false}){return <label className="ml-field"><span>{label}{required&&<small>必填</small>}</span>{area?<textarea name={name} aria-label={label} aria-required={required} value={value} maxLength={limit} rows={rows} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input name={name} aria-label={label} aria-required={required} value={value} maxLength={limit} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}<span className="ml-field-foot">{hint&&<em>{hint}</em>}{area&&<small>{value.length}/{limit}</small>}</span></label>;}
function Stepper({step}){return <ol className="ml-stepper">{['写给谁','留下你的故事','邀请怎样发生'].map((x,i)=><li key={x} aria-current={step===i?'step':undefined} className={step===i?'current':step>i?'done':''}><b>{step>i?<Check size={14}/>:String(i+1).padStart(2,'0')}</b><span>{x}</span></li>)}</ol>;}
function saveFile(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}

export function LetterApp({active=true}){
  const initial=useRef(null);if(initial.current===null)initial.current=restore()||{};
  const [view,setView]=useState(initial.current.view||'home');
  const [letter,setLetter]=useState(()=>initial.current.letter||createLetter());
  const [step,setStep]=useState(initial.current.step||0);
  const [demo,setDemo]=useState(initial.current.demo||false);
  const [reply,setReply]=useState(initial.current.reply||EMPTY_REPLY);
  const [ritualAnswer,setRitualAnswer]=useState(initial.current.ritualAnswer||'');
  const [error,setError]=useState(''),[toast,setToast]=useState(''),[modal,setModal]=useState(null),[items,setItems]=useState([]);
  const [transferText,setTransferText]=useState(''),[prepared,setPrepared]=useState(null),[showBefore,setShowBefore]=useState(false);
  const timer=useRef(null),fileInput=useRef(null),mainHeading=useRef(null),rootRef=useRef(null);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  useEffect(()=>{const root=rootRef.current;return()=>root?.querySelectorAll('audio').forEach(el=>el.pause());},[active]);
  useEffect(()=>{try{sessionStorage.setItem(SESSION_KEY,JSON.stringify({view,letter,step,demo,reply,ritualAnswer}));}catch{}},[view,letter,step,demo,reply,ritualAnswer]);
  useEffect(()=>{if(active){mainHeading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}},[view,step,active]);
  const notify=text=>{setToast(text);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),4500);};
  const move=next=>{setError('');setToast('');setView(next);setModal(null);};
  const update=(key,value)=>{setLetter(l=>({...l,[key]:value,updatedAt:Date.now()}));setError('');};
  const updateReply=(key,value)=>{setReply(r=>({...r,[key]:value}));setError('');};
  const safely=fn=>{try{return fn();}catch(e){setError(e.message||'这一步没有完成，请重试。');return false;}};
  const newLetter=()=>{setLetter(createLetter());setStep(0);setDemo(false);setReply(EMPTY_REPLY);move('compose');};
  const beginExample=()=>{const {status,...fields}=SAMPLE_FIELDS;setLetter({...createLetter(fields),status});setDemo(true);setReply(EMPTY_REPLY);setRitualAnswer('');move('receive');};
  const openInbox=()=>safely(()=>{setItems(listLetters());move('inbox');});
  const openSaved=item=>{setLetter(item);setDemo(item.title.startsWith('示例｜'));setStep(0);setReply(EMPTY_REPLY);move(item.status==='complete'?'result':item.status==='draft'?'compose':'invite');};
  const saveDraft=()=>safely(()=>{setLetter(saveLetter(letter));notify('草稿已保存到“我的信箱”');});
  const next=()=>safely(()=>{
    if(step===0&&(!letter.fromName.trim()||!letter.fromCity.trim()||!letter.toName.trim()))throw Error('先填上你的落款、所在城市和收信人的名字。');
    if(step===1&&(!letter.story.trim()||!letter.firstLine.trim()))throw Error('留下一段记忆，再写出属于你的上半句。');
    const saved=saveLetter(letter);setLetter(saved);setStep(s=>Math.min(2,s+1));setError('');
  });
  const seal=()=>safely(()=>{
    const complete={...letter,title:letter.title.trim()||`${letter.fromName}写给${letter.toName}的月光信`,status:'waiting',updatedAt:Date.now()};
    exportInvitation(complete);setLetter(saveLetter(complete));setDemo(false);move('invite');
  });
  const receiver=()=>{setReply(EMPTY_REPLY);setRitualAnswer('');move('receive');};
  const unfold=()=>{
    if(letter.opening==='question'&&!ritualAnswer.trim()){setError('写下你的回答，再打开这封信。');return;}
    setReply(r=>({...r,name:r.name||letter.toName,message:letter.opening==='question'?`${ritualAnswer.trim()}\n\n`:r.message}));move('read');
  };
  const finish=()=>safely(()=>{const result=submitReply(letter,reply);const existing=getLetter(result.id);if(existing?.status==='complete')throw Error('这封信已经有一份回信。请到信箱查看完整作品，或重新发起一封。');setLetter(saveLetter(result));setShowBefore(false);move('result');});
  const prepare=(kind)=>safely(()=>{const text=kind==='reply'?exportReply(letter):exportInvitation(letter);setPrepared({kind,text,name:`${kind==='reply'?'回信':'邀请'}-${letter.title}.moonletter.json`});setModal('export');});
  const copy=async text=>{try{await navigator.clipboard.writeText(text);notify('内容已复制，可以交给对方导入');}catch{notify('请展开内容并手动复制');}};
  const importText=text=>safely(()=>{
    if(new Blob([text]).size>65536)throw Error('这份文件过大，请选择月光来信的邀请或回信。');
    let data;try{data=JSON.parse(text);}catch{throw Error('内容格式不正确，请完整粘贴邀请或回信。');}
    if(data.kind==='moon-letter-reply'){
      const original=getLetter(data.reply?.letterId);if(!original)throw Error('这个浏览器没有对应的原信。请在写信人的设备导入这份回信。');
      if(original.status==='complete'){const checked=mergeReply({...original,status:'waiting',reply:null},text);if(JSON.stringify(checked.reply)!==JSON.stringify(original.reply))throw Error('这封信已有另一份回应，不能覆盖。');setLetter(original);setShowBefore(false);move('result');notify('这份回信已收录，已打开完整作品');return;}
      const merged=mergeReply(original,text);setLetter(saveLetter(merged));setShowBefore(false);setDemo(merged.title.startsWith('示例｜'));move('result');notify('回信已合入原信，两个人的作品完成了');
    }else{
      const incoming=importInvitation(text);const existing=getLetter(incoming.id);if(existing?.status==='complete'){setLetter(existing);move('result');notify('这封信已经完成，已打开收藏');return;}
      setLetter(incoming);setDemo(incoming.title.startsWith('示例｜'));setReply(EMPTY_REPLY);setRitualAnswer('');move('receive');
    }
    setTransferText('');
  });
  const readFile=async file=>{if(!file)return;if(file.size>65536)return setError('请选择64KB以内的月光来信文件。');try{importText(await file.text());}catch{setError('文件未能读取，请重新选择，或粘贴邀请内容。');}};
  const remix=()=>safely(()=>{setLetter(remixLetter(letter));setStep(0);setDemo(false);setReply(EMPTY_REPLY);move('compose');notify('玩法已保留，请换成你的收信人和故事');});
  const poem=LETTER_POEMS[letter.poemId];
  const sample={...SAMPLE_FIELDS,reply:{name:'小满',city:'上海',line:'你让上海的月亮有了回响。'},status:'complete'};
  const heading=(text,eyebrow)=><div className="ml-page-heading">{eyebrow&&<p className="ml-eyebrow">{eyebrow}</p>}<h1 ref={mainHeading} tabIndex={-1}>{text}</h1></div>;

  if(!active)return null;
  return <main className="ml-app" ref={rootRef}>
    <header className="ml-nav"><button className="ml-brand" onClick={()=>move('home')}><Moon size={24}/><span>月下造境</span><small>月光来信</small></button><nav aria-label="产品导航"><button aria-current={view==='home'?'page':undefined} onClick={()=>move('home')}>共写一轮月</button><button aria-current={view==='inbox'?'page':undefined} onClick={openInbox}>我的信箱</button><a href="#sea">灵感画布<ArrowUpRight size={14}/></a></nav><button className="ml-secondary ml-import-nav" onClick={()=>{setTransferText('');setError('');setModal('import');}}><EnvelopeOpen size={18}/>导入来信 / 回信</button></header>
    <input type="file" hidden ref={fileInput} accept=".json,.moonletter.json,application/json" onChange={e=>{readFile(e.target.files[0]);e.target.value='';}}/>
    {view==='home'&&<>
      <section className="ml-home-hero"><div className="ml-hero-copy"><p className="ml-eyebrow">中秋 · 给一段关系，留一个共同的作品</p><h1 ref={mainHeading} tabIndex={-1}>有些月光，<br/>要两个人<br/><em>一起写完。</em></h1><p className="ml-hero-description">你写下记忆和上半句，<br/>邀请一个人读信、续写。<br/>两座城市，两个人的字句，合成一封月光信。</p><div className="ml-hero-actions"><button className="ml-primary" onClick={newLetter}><PenNib size={19}/>写一封月光信<ArrowRight size={18}/></button><button className="ml-text-button" onClick={beginExample}>先体验一封来信<ArrowUpRight size={18}/></button></div><p className="ml-small">约 3 分钟写信 · 对方的回应，会真正进入作品</p></div><div className="ml-hero-art"><div className="ml-art-kicker"><span>一封信，如何变成两个人的作品</span><span>完成效果示例</span></div><LetterArtifact letter={sample} compact/><div className="ml-art-caption"><Users size={18}/><p>阿遥写下上句，小满补完下句。<br/><strong>两个人的名字，都留在这轮月光里。</strong></p><button aria-label="体验这封示例来信" onClick={beginExample}><ArrowUpRight size={25}/></button></div></div></section>
      <section className="ml-how" aria-label="创作流程"><article><span>01</span><div><h2>你先落笔</h2><p>选一句古诗，写一段只有你们懂的记忆。</p></div></article><article><span>02</span><div><h2>把下一句留给对方</h2><p>接诗、回答问题，再写下自己的回应。</p></div></article><article><span>03</span><div><h2>一起完成，继续生长</h2><p>收藏共同署名的作品，也能沿用玩法再创作。</p></div></article></section>
      <section className="ml-culture-strip"><BookOpen size={26}/><div><h2>从“天涯共此时”，到你们的此时此地。</h2><p>古诗是引子，你们的真实故事才是正文。每首诗保留作者与出处，原创句子单独署名。</p></div><button className="ml-text-button" onClick={()=>setModal('culture')}>看看文化线索<ArrowRight size={16}/></button></section>
    </>}

    {view==='compose'&&<section className="ml-compose"><div className="ml-compose-top"><button className="ml-text-button" onClick={()=>move('home')}><ArrowLeft size={17}/>回到首页</button><button className="ml-text-button" onClick={saveDraft}>保存草稿</button></div><Stepper step={step}/><div className="ml-compose-grid"><div className="ml-form-side">
      {step===0&&<>{heading('先想到一个人。','01 / 写给谁')}<p className="ml-lead">不必写给所有人。先写给那个，你想一起看月亮的人。</p><div className="ml-two-fields"><Field label="你的落款" name="fromName" value={letter.fromName} onChange={v=>update('fromName',v)} placeholder="你的名字或昵称" limit={24} required/><Field label="你所在的城市" name="fromCity" value={letter.fromCity} onChange={v=>update('fromCity',v)} placeholder="如：杭州" limit={30} required/></div><Field label="这封信写给谁" name="toName" value={letter.toName} onChange={v=>update('toName',v)} placeholder="对方的名字或昵称" limit={24} required/><div className="ml-field"><span>选一句诗，作为这封信的引子</span><div className="ml-poem-options">{Object.entries(LETTER_POEMS).map(([id,p])=><button className={letter.poemId===id?'selected':''} key={id} onClick={()=>update('poemId',id)} aria-pressed={letter.poemId===id}><strong>{p.line}</strong><span>{p.purpose}</span><small>{p.author}《{p.title}》</small>{letter.poemId===id&&<Check size={18}/>}</button>)}</div></div><button className="ml-text-button" onClick={()=>setModal('poem')}><BookOpen size={16}/>为什么是这句诗</button></>}
      {step===1&&<>{heading('把只有你们懂的，写下来。','02 / 留下你的故事')}<p className="ml-writing-prompt"><BookOpen size={18}/>{poem.prompt}</p><Field label="想让对方读到的一段记忆" name="story" value={letter.story} onChange={v=>update('story',v)} placeholder="从一件很小的事写起：一道菜、一条回家的路、一次没有说出口的告别……" area rows={6} limit={600} required/><Field label="你写的上半句" name="firstLine" value={letter.firstLine} onChange={v=>update('firstLine',v)} placeholder="例如：我把杭州的晚风写进月光，" area rows={2} limit={80} required hint="不用仿古，也不用押韵。对方会用自己的话接上下一句。"/><Field label="给这封信起个名字" name="title" value={letter.title} onChange={v=>update('title',v)} placeholder="如：等你补完，这一轮月亮" limit={60}/></>}
      {step===2&&<>{heading('把一半月光，交给对方。','03 / 邀请怎样发生')}<p className="ml-lead">你决定信怎样展开。对方决定下一句怎样继续。</p><fieldset className="ml-options"><legend>收信人怎样打开这封信</legend>{OPENINGS.map(o=><button key={o.id} className={letter.opening===o.id?'selected':''} aria-pressed={letter.opening===o.id} onClick={()=>update('opening',o.id)}><span><strong>{o.name}</strong><small>{o.detail}</small></span>{letter.opening===o.id?<Check size={20}/>:<ArrowRight size={18}/>}</button>)}</fieldset>{letter.opening==='question'&&<Field label="你想问对方的问题" name="question" value={letter.question} onChange={v=>update('question',v)} placeholder="还记得我们一起看过月亮的那个地方吗？" limit={100} required hint="这是读信的开场，不是需要答对的密码。"/>}<fieldset className="ml-style-choices"><legend>两个人的作品，以什么样子留下</legend>{LETTER_STYLES.map(s=><button key={s.id} aria-pressed={letter.style===s.id} className={letter.style===s.id?'selected':''} onClick={()=>update('style',s.id)}><img src={assetUrl(`/assets/${s.asset}.png`)} alt=""/><span>{s.name}{letter.style===s.id&&<Check size={15}/>}</span></button>)}</fieldset><div className="ml-next-person"><Users size={22}/><p><strong>{letter.toName||'收信人'}会补上什么？</strong><br/>所在城市、一句原创续写，以及给你的回信。它们会成为作品的一部分。</p></div></>}
      {error&&<p role="alert" className="ml-error">{error}</p>}<div className="ml-form-actions">{step>0?<button className="ml-secondary" onClick={()=>{setStep(s=>s-1);setError('');}}><ArrowLeft size={17}/>上一步</button>:<span/>}<button className="ml-primary" onClick={step<2?next:seal}>{step<2?'下一步':'封好这封信'}<ArrowRight size={18}/></button></div>
    </div><aside className="ml-preview-side"><div className="ml-art-kicker"><span>这封信，正慢慢成形</span><small>实时预览</small></div><LetterArtifact letter={letter} compact/><p><PenNib size={17}/>你的上半句在这里。另一半，留给对方。</p></aside></div></section>}

    {view==='invite'&&<section className="ml-invite-layout"><div>{heading('你的半封信，写好了。','邀请已准备 · 尚未发送')}<p className="ml-lead">接下来，把读信的位置留给{letter.toName}。<br/>对方续写以后，作品才会完整。</p><div className="ml-address"><span>从</span><strong>{letter.fromCity} · {letter.fromName}</strong><ArrowRight size={20}/><span>给</span><strong>{letter.toName}</strong></div><div className="ml-invite-actions"><button className="ml-primary" onClick={receiver}><EnvelopeOpen size={20}/>切换到收信人，体验完整流程</button><button className="ml-secondary" onClick={()=>prepare('invitation')}><Copy size={19}/>导出邀请文件</button></div><div className="ml-local-explainer"><h2>现在怎样交给另一个人？</h2><p>这版先支持本机体验和文件往返。复制或下载邀请内容，对方在本应用点“导入来信 / 回信”导入；完成后把回信内容交还给你。</p><p>线上链接和自动收信尚未接入。这里不会声称信已送达。</p></div><button className="ml-text-button" onClick={openInbox}>收进我的信箱<ArrowRight size={17}/></button></div><div><LetterArtifact letter={letter}/></div></section>}

    {view==='receive'&&<section className="ml-receive"><div className="ml-receive-meta"><span><EnvelopeOpen size={17}/>{demo?'示例来信 · 你来扮演收信人':'收信人视角'}</span><button className="ml-text-button" onClick={()=>move(demo?'home':'invite')}><ArrowLeft size={15}/>{demo?'回到首页':'回到写信人'}</button></div><div className="ml-letter-door"><div className="ml-door-art"><img src={assetUrl(`/assets/${letter.style==='paper'?'paper-scene':letter.style==='sound'?'sound-pool':'moon-sea'}.png`)} alt="月色中的来信"/><img className="ml-door-moon" src={assetUrl('/assets/moon.png')} alt=""/><p>{letter.fromCity}的月光，<br/>写着你的名字。</p></div><div className="ml-door-content"><p className="ml-eyebrow">给 {letter.toName} · 来自 {letter.fromName}</p><h1 ref={mainHeading} tabIndex={-1}>有一半故事，<br/>在等你。</h1><p className="ml-lead">{letter.fromName}留了一段记忆，也留了一个空位。<br/>读完信，写下你的那一半。</p>{letter.opening==='poem'?<div className="ml-poem-gate"><p>先接一句诗，让月光替你拆信。</p><h2>{poem.start}，</h2><div>{poem.options.map(option=><button className="ml-secondary" key={option} onClick={()=>{if(option===poem.answer)unfold();else setError('这句也有月意，但不是这首诗的下一句。再试一次，或看看提示。');}}>{option}</button>)}</div><details><summary>看看诗句提示</summary><p>{poem.line}</p><small>{poem.author}《{poem.title}》</small></details></div>:letter.opening==='question'?<div><Field label={letter.question} name="ritualAnswer" value={ritualAnswer} onChange={setRitualAnswer} area rows={3} limit={300} placeholder="写下你的答案，它也会留在回信里。"/><button className="ml-primary" onClick={unfold}>带着答案，打开信<ArrowRight size={18}/></button></div>:<button className="ml-primary" onClick={unfold}>打开这封月光信<ArrowRight size={18}/></button>}{error&&<p className="ml-error" role="alert">{error}</p>}<p className="ml-door-note">你的回应会成为共同作品的一部分。</p></div></div></section>}

    {view==='read'&&<section className="ml-reading"><div className="ml-reading-heading">{heading('这封信，写着你们的故事。','读信 → 续写 → 两人共同完成')}<p className="ml-small">{demo?'正在体验示例；下面的续写由你真正填写。':'收信人视角 · 写完以后，可以把回信交还给写信人。'}</p></div><div className="ml-reading-grid"><article className="ml-letter-paper"><p className="ml-eyebrow">{letter.fromCity}来信</p><h2>{letter.toName}，见字如晤。</h2><p className="ml-story">{letter.story}</p><blockquote><small>留给你续写的上半句</small>{letter.firstLine}</blockquote><div className="ml-signature"><span>{letter.fromName}</span><small>{letter.fromCity} · 中秋寄意</small></div><div className="ml-poem-footnote"><BookOpen size={18}/><p>{poem.line}<small>{poem.author}《{poem.title}》· 古诗引子</small></p></div></article><form className="ml-reply-form" onSubmit={e=>{e.preventDefault();finish();}}><div className="ml-reply-heading"><PenNib size={23}/><h2>现在，轮到你的那一半。</h2></div><p>你的句子、城市和落款会进入完整作品。</p><div className="ml-two-fields"><Field label="你的落款" name="replyName" value={reply.name} onChange={v=>updateReply('name',v)} limit={24} required/><Field label="你所在的城市" name="replyCity" value={reply.city} onChange={v=>updateReply('city',v)} placeholder="如：上海" limit={30} required/></div><Field label="接上你的下一句" name="replyLine" value={reply.line} onChange={v=>updateReply('line',v)} placeholder="用你自己的话，接住对方的心意。" area rows={2} limit={80} required/><Field label="也给对方回一封信" name="replyMessage" value={reply.message} onChange={v=>updateReply('message',v)} placeholder="那段记忆，在你心里是什么样子？或者告诉对方，你此刻最想说的话。" area rows={5} limit={600} required/>{error&&<p role="alert" className="ml-error">{error}</p>}<button type="submit" className="ml-primary">把两个人的月光合在一起<Heart size={18}/></button><small className="ml-small">这一步生成共同作品，并保存在当前浏览器。</small></form></div></section>}

    {view==='result'&&letter.reply&&<section className="ml-result"><div className="ml-result-heading"><div>{heading('这一轮月亮，你们写完整了。','已共同完成 · 两个名字，一件作品')}<p>{letter.fromCity}的{letter.fromName}，和{letter.reply.city}的{letter.reply.name}，各自留下了一句。</p></div><SealCheck size={42} weight="light"/></div><div className="ml-result-grid"><div><div className="ml-result-toggle" aria-label="查看作品变化"><button aria-pressed={showBefore} onClick={()=>setShowBefore(true)}>只有我的上半句</button><button aria-pressed={!showBefore} onClick={()=>setShowBefore(false)}>两个人完成之后<Check size={15}/></button></div><LetterArtifact letter={letter} showReply={!showBefore}/></div><aside className="ml-result-side"><h2>这一次，作品里多了什么？</h2><ol className="ml-contributions"><li><Check size={16}/><div><strong>{letter.fromName}留下了记忆与上句</strong><span>{letter.fromCity} · 写信人</span></div></li><li><Check size={16}/><div><strong>{letter.reply.name}补上了原创下句</strong><span>{letter.reply.city} · 共同创作者</span></div></li><li><Check size={16}/><div><strong>两封信、两座城市、共同署名</strong><span>已收藏在这个浏览器的信箱</span></div></li></ol><div className="ml-response-letter"><p className="ml-eyebrow">{letter.reply.name}的回信</p><p>{letter.reply.message}</p><small>{letter.reply.city} · {letter.reply.name}</small></div><div className="ml-result-actions"><button className="ml-primary" onClick={()=>prepare('reply')}><EnvelopeOpen size={19}/>导出回信文件</button><p className="ml-transfer-guidance">复制或下载后，请自行转交给写信人；对方导入后即可看到回应。</p><button className="ml-secondary" onClick={remix}><Plus size={18}/>再给一个人写信</button><button className="ml-text-button" onClick={openInbox}><Mailbox size={18}/>到我的信箱查看</button></div></aside></div><details className="ml-original-letter"><summary>再读一次原信 · {letter.title}</summary><p>{letter.story}</p></details></section>}

    {view==='inbox'&&<section className="ml-inbox"><div className="ml-inbox-heading">{heading('把想念，收藏在这里。','我的信箱 · 当前浏览器')}<button className="ml-primary" onClick={newLetter}><Plus size={18}/>写一封新的</button></div>{items.length?<div className="ml-letter-list">{items.map(item=><button key={item.id} className="ml-inbox-item" onClick={()=>openSaved(item)}><img src={assetUrl(`/assets/${item.style==='paper'?'paper-scene':item.style==='sound'?'sound-pool':'moon-sea'}.png`)} alt=""/><div><span className={`ml-status ${item.status}`}>{item.status==='complete'?'两人已共同完成':item.status==='waiting'?'邀请已准备 · 待回信':'草稿'}</span><h2>{item.title||'一封还没落款的信'}</h2><p>{item.fromName||'你'} {item.fromCity&&`· ${item.fromCity}`}<ArrowRight size={15}/>{item.reply?.name||item.toName||'等你写上名字'}</p><small>{item.firstLine||'从一段记忆开始。'}</small></div><ArrowUpRight size={22}/></button>)}</div>:<div className="ml-empty"><Mailbox size={52} weight="light"/><h2>第一封信，等你落笔。</h2><p>写下一个人和一段记忆，再把下一句留给对方。</p><button className="ml-primary" onClick={newLetter}>开始写信<ArrowRight size={18}/></button></div>}<p className="ml-inbox-note">邀请尚未接入在线送达。收到对方的回信内容后，点击“导入来信 / 回信”导入，就会合入原信。</p></section>}

    {error&&['home','inbox','invite','result'].includes(view)&&!modal&&<p className="ml-error ml-global-error" role="alert">{error}</p>}
    <footer className="ml-footer"><span>月下造境 · 让团圆，有你们自己的写法</span><span>本机体验版 · 作品保存在当前浏览器</span></footer>
    {toast&&<p role="status" className="ml-toast"><Check size={18}/>{toast}</p>}
    {modal==='poem'&&<Dialog title={`从《${poem.title}》出发`} onClose={()=>setModal(null)}><p className="ml-dialog-verse">{poem.line}</p><p className="ml-small">{poem.author}</p><p>{poem.note}</p><a className="ml-text-button" href={poem.source} target="_blank" rel="noreferrer">阅读文化资料<ArrowUpRight size={16}/></a></Dialog>}
    {modal==='culture'&&<Dialog title="月圆的节日，写给具体的人" onClose={()=>setModal(null)}><p>中秋习俗包含赏月、祭月、吃月饼等。我们从共同望月与团圆的文化意涵出发，把“给远方的人留一句话”变成一次共同创作。</p><div className="ml-culture-list">{Object.values(LETTER_POEMS).map(p=><article key={p.title}><h3>{p.line}</h3><p>{p.note}</p><a href={p.source} target="_blank" rel="noreferrer">{p.author}《{p.title}》<ArrowUpRight size={14}/></a></article>)}</div><a href="https://www.ihchina.cn/art/detail/id/9463.html" target="_blank" rel="noreferrer" className="ml-text-button">中秋节习俗资料 · 中国非物质文化遗产网<ArrowUpRight size={16}/></a></Dialog>}
    {modal==='import'&&<Dialog title="打开邀请，或收下回信" onClose={()=>{setModal(null);setError('');}}><p>把对方给你的完整内容粘贴在这里，或选择邀请／回信文件。</p><textarea className="ml-transfer" aria-label="邀请或回信内容" value={transferText} onChange={e=>setTransferText(e.target.value)} placeholder="粘贴完整的月光来信内容…"/><div className="ml-dialog-actions"><button className="ml-secondary" onClick={()=>fileInput.current.click()}><FolderOpen size={18}/>选择文件</button><button className="ml-primary" onClick={()=>importText(transferText)} disabled={!transferText.trim()}>打开内容<ArrowRight size={18}/></button></div>{error&&<p className="ml-error" role="alert">{error}</p>}</Dialog>}
    {modal==='export'&&prepared&&<Dialog title={prepared.kind==='reply'?'把你的回信，交还给对方':'把下一句，留给另一个人'} onClose={()=>setModal(null)}><p>{prepared.kind==='reply'?'写信人在原设备打开本应用，点“导入来信 / 回信”，导入这份内容，两个人的作品就会合在一起。':'收信人在能运行本应用的设备上，点“导入来信 / 回信”，导入这份内容，就能读信并续写。'}</p><div className="ml-dialog-actions"><button className="ml-primary" onClick={()=>copy(prepared.text)}><Copy size={18}/>复制{prepared.kind==='reply'?'回信':'邀请'}内容</button><button className="ml-secondary" onClick={()=>{saveFile(prepared.text,prepared.name);notify('已请求下载，也可以复制内容交给对方');}}><DownloadSimple size={18}/>下载文件</button></div><details><summary>查看完整内容，也可手动复制</summary><textarea className="ml-transfer" aria-label="已准备的作品内容" readOnly value={prepared.text} onFocus={e=>e.target.select()}/></details><p className="ml-transfer-note">当前没有向任何人发送消息。文件包含信中文字；请交给你想邀请的人。</p></Dialog>}
  </main>;
}
